# Generated by Django 5.0.1 on 2024-02-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('pracid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prac_phone', models.CharField(max_length=200)),
                ('prac_email', models.CharField(max_length=200)),
                ('prac_name', models.CharField(max_length=200)),
                ('prac_address', models.CharField(max_length=200)),
                ('prac_city', models.CharField(max_length=50)),
                ('prac_region', models.CharField(max_length=100)),
                ('prac_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('prid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
